### PR TITLE
Display images from Gravatar

### PR DESCRIPTION
**Pull request by schmiddim**
Hi, 

I put  images from gravatar  to your nice project - make a merge if you like it. 

Cheers

### CODE REVIEW

**Comment by divbyzero** [comment]
Hi! Did you merge this code with master branch?

**Comment by docwhat** [comment]
@fguillot Did you close this by accident? Or are you rejecting this?

**Comment by fguillot** [comment]
This code is not merged.

I'm sorry for the contributor, I don't even remember why I closed this pull-request. Probably, a mistake. I have nothing against that.

The code need to be improved to be included with the current master. I will try to update the code and see if that work well.

**Comment by schmiddim** [comment]
Hi,
sorry for the code quality - that wasn't my brightest day. Will create a further pull request for you at the weekend.

**Comment by fguillot** [comment]
Merged manually in master.

**Comment by divbyzero** [comment]
Thanks!

**Pull request closed without merging**
