### PR TITLE
Please add my code to your master

### PR DESCRIPTION
**Pull request by Kolesar**
Dear,

As you can see I changed something about:
**overdue tasks** and added two new options:
--group - group all overdue tasks for all projects in one email
--admin - get all overdue tasks for selected project

**translation**
added new translation for Bosnian language

**fix about destroy session**
detect that message in debug log

**adapt code for new functionalities**

### CODE REVIEW

**Comment by fguillot** [comment]
There are conflicts detected in your pull-request, you should update your local branch with master.

**Comment by fguillot** [comment]
By the way, you should refactor the method `sendOverdueTaskNotifications`, there is too much code in it and you should not depend of `Symfony\Component\Console\Input\InputInterface` in a model.

And it would be better to send a separate pull-request only for the new translation so I can merge that one quickly.

Thanks

**Comment by fguillot** [comment]
I added your Bosnian translation in master but the rest need to be fixed to be merged.

Thanks

**Comment by Kolesar** [comment]
Dear, 

As you can see I synced my code with your and please merge code now.

**Comment by Kolesar** [comment]
Hi Frédéric,

Please add this code in your branch. I need new functionalities, specially for overdue tasks.

BR

**Comment by waja** [comment]
> Please add this code in your branch. I need new functionalities, specially for overdue tasks.

Sorry, but if I would maintain this project, I would be not very motivated to merge your changes by such a behaviour. If you need this so urgent, what is holding you back to use your own fork and merge upstream changes regularly back?

**Comment by Kolesar** [comment]
I agree with you. Do not worry. If you require that I need change my code, adapt, whatever, please tell me.

I used my fork of course, ...

BR

**Comment by Kolesar** [comment]
Dear,

As you can see I added new functionalities:
* task can be search by comments
* activities are searchable now
* added quick link (option) for adding child task

BR

**Comment by fguillot** [comment]
If you would like to have your pull-request merged into master you have to fix the issues mentioned in previous comments.

- Send a pull-request by feature/subject, smaller PR are easier to review, here you have 4 or 5 different subjects in a single PR
- The unit tests are broken with your changes, all tests must pass
- There are 24 commits here, try to have one single clean commit by PR

Thanks for your cooperation.

**Pull request closed without merging**
