### PR TITLE
Task age and days in column show hours if < 1 day

### PR DESCRIPTION
**Pull request by ashbike**
Sending this pull request though I'm not very happy with this code change because of these reasons.

- Put the function in app/functions.php. Not sure if this is the right place. 
- Now it does not do any dynamic formatting. It's always <1h, NNh and NNd. 

It's functional, but I think the code can be improved.

### CODE REVIEW

**Comment by BlueTeck** [comment]
:+1:

**Comment by mkresin** [comment]
> Now it does not do any dynamic formatting.

You might want to have a look at the following code from frédéric's other project miniflux https://github.com/fguillot/miniflux/blob/master/lib/helpers.php#L137

**Comment by ashbike** [comment]
:+1: That's what I was looking for. New to PHP. Any advice which file this function will go into? Then I will make changes and send another pull request.

**Comment by fguillot** [comment]
I merged and modified your pull-request (move the function to the right place and the text can be translated).

Note: Template helper functions go to `app\Core\Helper.php`.

**Pull request merged**
