### PR TITLE
duplicate project metadata when duplicating project

### PR DESCRIPTION
**Pull request by Busfreak**
regarding issue https://github.com/fguillot/kanboard/issues/2043

### CODE REVIEW

**Comment by fguillot** [comment]
Where are the unit tests?

**Comment by Busfreak** [comment]
No new tests, fixed existing test testGetSelections in ProjectDuplicationTest

**Comment by Busfreak** [comment]
@fguillot 
Is there anything missing which prevents you from merging this PR?

**Comment by fguillot** [comment]
You added a new method but no test for this method. Anyway, it's merged now.

**Comment by Trudill** [comment]
Hi,
First, thanks for the amazing job you are doing !

Sorry, I don't get it. Was it solved in the master ?

It would be nice to add this feature ;) I am on 1.0.41. But metadata doesn't appear as checkbox.

I have :
Permissions
Categories
Tags
Actions
Tasks

But no Metadata.

Have a nice day

**Pull request merged**
