### PR TITLE
update german translation, fixed 'BAM - Konvertibile Mark'

### PR DESCRIPTION
**Pull request by Busfreak**
Hi,
I've updated german translation for upcoming 1.0.22.
Also changed "Konvertibile Mark" to "Kovertible Mark" :-)
Regards
Martin

### CODE REVIEW

**Comment by fguillot** [comment]
Thanks!

**Comment by Busfreak** [comment]
Sorry, mistake in UTF-8, sending new one

**Comment by Busfreak** [comment]
Ok, you already got it :-)

**Comment by BlueTeck** [comment]
:+1:

**Pull request merged**
