### PR TITLE
Requirement of assign time table by user itself

### PR DESCRIPTION
**Pull request by kasunf**
userHelper.php class and UserSession.php files are changed to accommodate the requirement of assign time table by user itself.

also   Timetable\Template\user\sidebar.php file changed in time table plugin.

as follows

<?php if ($this->user->isUser()): ?>
    <li <?= $this->app->getRouterController() === 'timetable' ? 'class="active"' : '' ?>>
        <?= $this->url->link(t('Manage timetable'), 'timetable', 'index', array('plugin' => 'timetable', 'user_id' => $user['id'])) ?>
    </li>
<?php endif ?>

### CODE REVIEW

**Comment by kasunf** [comment]
Please Review & Merge

**Comment by macman31** [comment]
@kasunf how do you expect @fguillot to review your pull request?
You changed all the lines endings in the modified files to CR LF (\r\n) instead of just LF (\n), resulting in a diff which encompasses all the files.....

**Comment by kasunf** [comment]
@macman31 i didn't do  it intentionally, may be i used wordpad to do the changes,i ll check and try to correct it.

**Comment by kasunf** [comment]
corrected.
https://github.com/fguillot/kanboard/pull/2414/files

**Pull request closed without merging**
