### PR TITLE
 Editing a task to move swimlanes #1705 

### PR DESCRIPTION
**Pull request by Busfreak**
This pull request resolves issue https://github.com/fguillot/kanboard/issues/1705 and https://github.com/fguillot/kanboard/issues/696.

It adds a selector for swimlanes and the possibility to edit the estimated time in edit_task.

### CODE REVIEW

**Comment by Busfreak** [comment]
updated for current codebase (1.0.25), so it's mergeable again

**Comment by fguillot** [comment]
Adding the missing form element on the edit page is not enough. It's not available yet on the form because the task positions needs to be updated in the column source and destination.

Another approach might be to add a new page just to move a task by choosing the column/swimlane...

**Comment by Busfreak** [comment]
OK, I will try a plugin.
THX

**Comment by SchmilK** [comment]
A different user experienced the "how do I move a task to an item at the bottom of a swimlane?" today.  
Simply grabbing the task, then using the keyboard arrow keys scrolled the page down and he was able to  move it to a swimlane at the bottom of the screen.

**Pull request closed without merging**
