### PR TITLE
new calendar view #383

### PR DESCRIPTION
**Pull request by BlueTeck**
I have made a new pull request, now it is mergeable and only 1 commit ;)

Waiting for your comments.

### CODE REVIEW

**Comment by BlueTeck** [comment]
I will improve the coding by myself in the next days.

**Comment by BlueTeck** [comment]
I have changed the code, but i will do more improvements later.

**Comment by fguillot** [comment]
Your pull-request will be integrated for the next version. For now, I'm testing the current master for the next couple of days before to release a new stable version.

**Comment by BlueTeck** [comment]
I will close this Pull Request and make a new one, because i developed in the master branch and I will contribute the german translation before release. So i have to organize my git better ;)

**Pull request closed without merging**
