### PR TITLE
New calendar view

### PR DESCRIPTION
**Pull request by BlueTeck**
new request for #470 that fits into master

### CODE REVIEW

**Comment by BlueTeck** [comment]
I had some new ideas, that i will implement:
- use same filters like the board and save selection (localstorage)
- a button to reset all filters
- refresh calander periodically like the board

**Comment by BlueTeck** [comment]
Removed Merge conflicts, added the things i wanted, now its your turn ;)

**Comment by oparoz** [comment]
For people reviewing, this is an implementation of https://github.com/fguillot/kanboard/issues/383

@BlueTeck - I think it's usually best to commit unrelated changes in separate PRs. It's easier for people to review that way. In this instance, the swimlane colour option is probably great, but in a separate PR, people would be able to make suggestions :)

**Comment by BlueTeck** [comment]
@oparoz the swimlane color option is a filter in the calendar view, so its correct here ;)

**Comment by oparoz** [comment]
Ah, cool :)

**Comment by BlueTeck** [comment]
screen1

**Comment by fguillot** [comment]
cool, give me the week to review and test that.

**Comment by fguillot** [comment]
I merged and improved your pull-request. Let me know if there is any issue.

**Comment by BlueTeck** [comment]
:thumbsup: nice code enhancements :)

**Pull request closed without merging**
