### PR TITLE
fixed preview images size on hover

### PR DESCRIPTION
**Pull request by lyoshaprikhodko**
Size changing on hovering is now fixed. (hope that was not a feature)

### CODE REVIEW

**Comment by BlueTeck** [comment]
It was a feature :-)

**Comment by semka** [comment]
It is very annoying feature :)

**Comment by Chiliec** [comment]
I agree, it's very uncomfortable when you want to open image in modal window and button run away from cursor.

**Comment by Konshin** [comment]
agree ^

**Comment by BlueTeck** [comment]
Okay, if you want, we could remove it, but this pull request ist not the right way, i could do it by my own. i will change it with the #717 enhancement next week.

**Comment by semka** [comment]
Awesome, thanks a lot. Our testing team goes mad every time they need to click on preview :)

**Comment by BlueTeck** [comment]
I have created a PR for that #782

**Comment by fguillot** [comment]
I merged #782

**Pull request closed without merging**
