### PR TITLE
Update TaskExport.php

### PR DESCRIPTION
**Pull request by Folcky**
Changed assignee_username to human name instead of username.

### CODE REVIEW

**Comment by BlueTeck** [comment]
Maybe this should be configurable for Kanboard, also for the Board assignee name etc...

**Comment by Folcky** [comment]
Why do you need username in the report? 
For example in transition export we can see that assignee name is a human name of an user.

I generate report every week and manually replace username with name :(. 
I dont understand for what purpose we need an option to configure that simple thing...

**Comment by fguillot** [comment]
In this case it's probably better to add a new column in the export with the full assignee name.

Replacing the column username by the full name remove a feature that may necessary by other Kanboard users.

**Comment by fguillot** [comment]
Now in master, the export show the assignee name and username.

**Pull request closed without merging**
