### PR TITLE
#1861 user and date for metadata

### PR DESCRIPTION
**Pull request by BlueTeck**
#1861 user and date for metadata

### CODE REVIEW

**Comment by fguillot** [comment]
- The CI build doesn't pass, there is a typo in your unit test.
- Why do you need to have application metadata, is that not the same thing as the settings table?
- What do you think about extending the abstract class `Model\Metadata` to avoid code duplication?

Thanks for submitting a pull-request.

**Comment by BlueTeck** [comment]
1. I will fix it
2. oh yes it is
3. I didn't use the class because you don't need the entity type/id for application settings

I will change 1 and 2, but what is your proposal about 3?

**Comment by BlueTeck** [comment]
Changed it

**Comment by BlueTeck** [comment]
Changed and rebased

**Pull request merged**
