### PR TITLE
#1245 bug with subtask timer

### PR DESCRIPTION
**Pull request by ukko**
Corrected recursive save Subtask, status change Subtask

### CODE REVIEW

**Comment by ukko** [comment]
Link on original Issue #1245

**Comment by fguillot** [comment]
How can I validate your bug fix? What are the steps to reproduce the issue?

**Comment by ukko** [comment]
Hello!

By steps:

* Create new project
* Create new task
* Create new subtask
* Change status subtask (?controller=subtask&action=toggleStatus&task_id=39&subtask_id=16&redirect=task)
* Waiting more than 15 minutes...
* Change status subtask
* Start the recursive calls and comes 500 error from the server

**Comment by ukko** [comment]
```
2015/09/28 11:05:01 [error] 1140#0: *73 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /home/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php on line 214
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /home/www/kanboard/index.php:0
PHP message: PHP   2. Core\Router->dispatch() /home/www/kanboard/index.php:5
PHP message: PHP   3. Controller\Subtask->toggleStatus() /home/www/kanboard/app/Core/Router.php:226
PHP message: PHP   4. Model\Subtask->toggleStatus() /home/www/kanboard/app/Controller/Subtask.php:183
PHP message: PHP   5. Model\Subtask->update() /home/www/kanboard/app/Model/Subtask.php:376
PHP message: PHP   6. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/kanboard/app/Model/Subtask.php:248
PHP message: PHP   7. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP message: PHP   8. call_user_func:{/home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164}() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP   9. Subscriber\SubtaskTimeTrackingSubscriber->logStartEnd() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  10. Model\SubtaskTimeTracking->logEndTime() /home/www/kanboard/app/Subscriber/SubtaskTimeTrackingSubscriber.php:44
PHP message: PHP  11. Model\SubtaskTimeTracking->updateSubtaskTimeSpent() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:280
PHP message: PHP  12. Model\Subtask->update() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:348
PHP message: PHP  13. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/kanboard/app/Model/Subtask.php:248
PHP message: PHP  14. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP message: PHP  15. call_user_func:{/home/www/kanboard/ven
2015/09/28 11:05:01 [error] 1140#0: *73 FastCGI sent in stderr: "/EventDispatcher.php:164
PHP message: PHP  30. Subscriber\SubtaskTimeTrackingSubscriber->logStartEnd() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  31. Model\SubtaskTimeTracking->logEndTime() /home/www/kanboard/app/Subscriber/SubtaskTimeTrackingSubscriber.php:44
PHP message: PHP  32. Model\SubtaskTimeTracking->updateSubtaskTimeSpent() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:280
PHP message: PHP  33. Model\Subtask->update() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:348
PHP message: PHP  34. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/kanboard/app/Model/Subtask.php:248
PHP message: PHP  35. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP message: PHP  36. call_user_func:{/home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164}() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  37. Subscriber\SubtaskTimeTrackingSubscriber->logStartEnd() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  38. Model\SubtaskTimeTracking->logEndTime() /home/www/kanboard/app/Subscriber/SubtaskTimeTrackingSubscriber.php:44
PHP message: PHP  39. Model\SubtaskTimeTracking->updateSubtaskTimeSpent() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:280
PHP message: PHP  40. Model\Subtask->update() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:348
PHP message: PHP  41. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/kanboard/app/Model/Subtask.php:248
PHP message: PHP  42. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP message: PHP  43. call_user_func:{/home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164}() /home/www/kanboard/vendor/symfon
2015/09/28 11:05:01 [error] 1140#0: *73 FastCGI sent in stderr: "tEnd() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  59. Model\SubtaskTimeTracking->logEndTime() /home/www/kanboard/app/Subscriber/SubtaskTimeTrackingSubscriber.php:44
PHP message: PHP  60. Model\SubtaskTimeTracking->updateSubtaskTimeSpent() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:280
PHP message: PHP  61. Model\Subtask->update() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:348
PHP message: PHP  62. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/kanboard/app/Model/Subtask.php:248
PHP message: PHP  63. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP message: PHP  64. call_user_func:{/home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164}() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  65. Subscriber\SubtaskTimeTrackingSubscriber->logStartEnd() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  66. Model\SubtaskTimeTracking->logEndTime() /home/www/kanboard/app/Subscriber/SubtaskTimeTrackingSubscriber.php:44
PHP message: PHP  67. Model\SubtaskTimeTracking->updateSubtaskTimeSpent() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:280
PHP message: PHP  68. Model\Subtask->update() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:348
PHP message: PHP  69. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/kanboard/app/Model/Subtask.php:248
PHP message: PHP  70. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP message: PHP  71. call_user_func:{/home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164}() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  72. Subscriber\SubtaskTimeTrackingS
2015/09/28 11:05:01 [error] 1140#0: *73 FastCGI sent in stderr: "ssage: PHP  87. Model\SubtaskTimeTracking->logEndTime() /home/www/kanboard/app/Subscriber/SubtaskTimeTrackingSubscriber.php:44
PHP message: PHP  88. Model\SubtaskTimeTracking->updateSubtaskTimeSpent() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:280
PHP message: PHP  89. Model\Subtask->update() /home/www/kanboard/app/Model/SubtaskTimeTracking.php:348
PHP message: PHP  90. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/kanboard/app/Model/Subtask.php:248
PHP message: PHP  91. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:53
PHP message: PHP  92. call_user_func:{/home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164}() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  93. Subscriber\SubtaskTimeTrackingSubscriber->logStartEnd() /home/www/kanboard/vendor/symfony/event-dispatcher/EventDispatcher.php:164
PHP message: PHP  94. Model\Subtask->getById() /home/www/kanboard/app/Subscriber/SubtaskTimeTrackingSubscriber.php:34
PHP message: PHP  95. PicoDb\Table->eq() /home/www/kanboard/app/Model/Subtask.php:162
PHP message: PHP  96. PicoDb\Table->__call() /home/www/kanboard/app/Model/Subtask.php:162
PHP message: PHP  97. call_user_func_array:{/home/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Table.php:644}() /home/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Table.php:644
PHP message: PHP  98. PicoDb\Condition->eq() /home/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Table.php:644
PHP message: PHP  99. PicoDb\Database->escapeIdentifier() /home/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Condition.php:145" while reading response header from upstream, client: 127.0.0.1, server: kanboard.local, request: "GET /?controller=subtask&action=toggleStatus&task_id=39&subtask_id=16&redirect=task HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "kanboard.local"
```

**Comment by fguillot** [comment]
If you are able to modify your patch to replace the method argument `array $options = null` by a flag `$fire_events = true` that would be great, so I can merge this bug fix. Thanks.

**Comment by ukko** [comment]
ok, of course

**Pull request merged**
