### PR TITLE
Activity redesign

### PR DESCRIPTION
**Pull request by mcorteel**
See #2018.

### CODE REVIEW

**Comment by mcorteel** [comment]
I also adapted the comments for better integration.

**Comment by froschdesign** [comment]
And what we see without Gravatar?

**Comment by mcorteel** [comment]
There is nothing when the integration is disabled:
spectacle x15974
If the integration is enabled, the avatars are displayed:
spectacle h15974

**Comment by froschdesign** [comment]
@mcorteel 
> There is nothing when the integration is disabled

Bad! :-1: 

You solution needs an external service and is restricted to a Gravatar.

[The first letter of the name is a good idea.](https://github.com/fguillot/kanboard/issues/126#issuecomment-115278666) This should be the standard implementation.
Gravatar or other services should be integrated via Plugin.

**Comment by mcorteel** [comment]
This is just a redesign, I haven't changed anything else.
This follows the current avatar principle (if gravatar integration is enabled, it displays the avatar if available).
Displaying something when gravatar is disabled would be another pull request (I plan on making a proposal if this is merged, but it has to be merged first).

**Comment by froschdesign** [comment]
> This is just a redesign, I haven't changed anything else.

Then we need to rethink here

**Comment by mcorteel** [comment]
Please comment on issue #126 for that.

**Comment by froschdesign** [comment]
A deeper integration of the Gravatar service in the core is the wrong way! (imo)

And "There is nothing when the integration is disabled" is not a nice idea.

**Comment by mcorteel** [comment]
This is not the subject of this pull request, please comment on #126.

**Comment by froschdesign** [comment]
> This is not the subject of this pull request…

"Show a Gravatar image or nothing" is not the topic?!

**Comment by mcorteel** [comment]
No, it's not. This is the topic of #126, which will in turn be the topic of **another** pull request (if and when this one is merged). I haven't changed the behavior here.
Basically, you are telling the painter that you want another socket to plug in your toaster when he's asking you about the color of the walls. Please wait for the meeting with the electrician to talk about that.
If it helps, I do agree with you. It just isn't the right place to discuss this.

**Comment by mcorteel** [comment]
@fguillot I see that you are partially redesigning the activity feed with the new (awesome) avatar feature. Don't you want to consider this pull request?

**Comment by Kolesar** [comment]
Can we group activities?
I made few changes about this. Make a pagination, searchable and order by activity ID (it is by date) and order by Task ID, but from my perspective better way (exactly I want to see that solution :) ) is the grouping by date and by task in expandable list.

**Comment by fguillot** [comment]
@mcorteel Thanks for submitting a pull-request and sorry about the delay of my answer.

As you can see, I also updated the activity stream to display the default avatar. Actually, that looks like that in master:

mon_flux_d_activite

Since everybody have different personal taste about the design, I prefer to keep it simple as it right now. 

But, if you prefer your own design, you still have the possibility to make a "theme plugin". I will be happy to publish it on the website.

Thanks.

**Comment by mcorteel** [comment]
Thanks, I will look into it!

**Pull request closed without merging**
